# ===============================
# DataSource Configuration (Supabase PostgreSQL)
# ===============================
server.port=${PORT:8080}

# Supabase Session Pooler JDBC connection string
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require&pgbouncer=true
spring.datasource.username=postgres.wbroqzcarcgzkhdvnmuk
spring.datasource.password=Mentorkrishdb

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=TRACE
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=20000

logging.level.com.zaxxer.hikari=DEBUG



# show full errors in response (DEV only!)
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.root=DEBUG
spring.mvc.log-request-details=true


# ===============================
# Other application configs
# ===============================

app.upload.dir=uploads

jwt.secret=gx02s4HMWk4WGhfg3vyElafDWMqtwmpG5gl1R/+gOQebnsYETaumStnx17EbgvNyJrRfiaJVNfrd2+gBjdKsiQ==
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.otp.expMinutes=5
app.otp.cooldownSeconds=60

app.otp.senderEmail=noreplymentorkrish@gmail.com
app.otp.senderName=Mentor Krish

#brevo.api.key=${BERVO_API_KEY}
#
#cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api_key=${CLOUDINARY_API_KEY}
#cloudinary.api_secret=${CLOUDINARY_API_SECRET}


brevo.api.key=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

cloudinary.cloud_name=da3ym2ykg
cloudinary.api_key=736862239554411
cloudinary.api_secret=Ki_hUlhP-BZ5sYWNEMBzoInTRUU
