# ===============================
# DataSource Configuration (Supabase PostgreSQL)
# ===============================
server.port=${PORT:8080}

# Supabase Session Pooler JDBC connection string
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=${SPRING_DATASOURSE_USERNAME}
spring.datasource.password=${SPRING_DATASOURSE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10

# ===============================
# Other application configs
# ===============================

app.upload.dir=uploads

jwt.secret=gx02s4HMWk4WGhfg3vyElafDWMqtwmpG5gl1R/+gOQebnsYETaumStnx17EbgvNyJrRfiaJVNfrd2+gBjdKsiQ==
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.otp.expMinutes=5
app.otp.cooldownSeconds=60

app.otp.senderEmail=noreplymentorkrish@gmail.com
app.otp.senderName=Mentor Krish

brevo.api.key=${BERVO_API_KEY}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}


